// Mocks generated by Mockito 5.4.6 from annotations
// in poke_app/test/features/home/presentation/notifier/home_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_app/features/home/data/models/all_pokemons_response.dart'
    as _i2;
import 'package:poke_app/features/home/data/models/pokemon_response.dart'
    as _i6;
import 'package:poke_app/features/home/domain/usecases/filter_pokemons_by_types_usecase.dart'
    as _i5;
import 'package:poke_app/features/home/domain/usecases/get_all_pokemon_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAllPokemonsResponse_0 extends _i1.SmartFake
    implements _i2.AllPokemonsResponse {
  _FakeAllPokemonsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllPokemonUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllPokemonUsecase extends _i1.Mock
    implements _i3.GetAllPokemonUsecase {
  MockGetAllPokemonUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AllPokemonsResponse> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.AllPokemonsResponse>.value(
              _FakeAllPokemonsResponse_0(this, Invocation.method(#call, [])),
            ),
          )
          as _i4.Future<_i2.AllPokemonsResponse>);
}

/// A class which mocks [FilterPokemonsByTypesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterPokemonsByTypesUsecase extends _i1.Mock
    implements _i5.FilterPokemonsByTypesUsecase {
  MockFilterPokemonsByTypesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Set<_i6.PokemonResponse>> call(Iterable<String>? types) =>
      (super.noSuchMethod(
            Invocation.method(#call, [types]),
            returnValue: _i4.Future<Set<_i6.PokemonResponse>>.value(
              <_i6.PokemonResponse>{},
            ),
          )
          as _i4.Future<Set<_i6.PokemonResponse>>);
}
